spring:
  application:
    name: Booking-Management-App-Prod

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      timeout: 6000ms
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 8
          max-wait: 5000ms

  mail:
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: ""

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          ssl:
            trust: ""

  springdoc:
    swagger-ui:
      enabled: true
      disable-swagger-default-url: true
    api-docs:
      enabled: true

app:
  base-url: ${BASE_URL}
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration: ${JWT_ACCESS_EXPIRATION}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION}
    token:
      password-reset: ${PASSWORD_RESET_TOKEN}
  payments:
    stripe:
      api-key: ${STRIPE_API_KEY}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  cloud:
    cloudinary:
      cloud-name: ${CLOUDINARY_CLOUD_NAME}
      api-key: ${CLOUDINARY_API_KEY}
      api-secret: ${CLOUDINARY_SECRET_KEY}


logging:
  level:
    root: warn
    org.springframework: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    com.axconstantino.reservationsystem: debug
  file:
    name: /var/log/app/booking-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true