spring:
  application:
    name: Booking-Management-App-Dev
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      lettuce:
        shutdown-timeout: 100ms

  mail:
    host: smtp.gmail.host
    port: 587
    username: olveraconstantinoaxel@gmail.com
    password: gozb gvjy iofv vnpm
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  base-url: http://localhost:3000
  jwt:
    secret: 51f1ebd91950319c7c05dfff4bfed4e89535eeccc9d8336c45de6150216e0cd97c3cc9041b5fdf3cad8631069dccc2fd7800e623446ffc78ab85184580cb9f9b2eed98a27c429fbc5974b16cef1a7a3a820f49568994039b4b1e5c1b28a5841023e7344583feae70f520a13789244edf769cf025bf16ea5d93d199b3b00d15fa87df8fa1be3514a3d0cbd4d67edb482597a1882e8c2fc7b62534853530e500b7b451c5fd2616d3c2778af628e2ce14210c4719649116abec8392564c653983e6580c148e7172ca1a61ff96efb58c0b254a237a0b07081b5762d75ac2a657489e1c9147dff1d7f7fd0afae53131b6c4bb1dcf75fec4e11af3ad237b95128b8f55
    access-expiration: 86400
    refresh-expiration: 604800
  stripe:
    api-key: ${STRIPE_API_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  cloudinary:
    cloud-name: ${CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    secret-key: ${CLOUDINARY_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

  springdoc:
    swagger-ui:
      enabled: true
      try-it-out-enabled: true
      persistAuthorization: true
    api-docs:
      enabled: true
    info:
      title: Portfolio API - DEV
      version: 1.0.0
      description: API Documentation (Development Environment)
      contact:
        name: Axel Constantino Olvera
        email: constantinoolveraa@gmail.com

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.axconstantino.reservationsystem: debug