spring:
  application:
    name: Booking-Management-App-Prod

  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      timeout: 6000ms
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 8
          max-wait: 5000ms

  mail:
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com

---
spring:
  config:
    activate:
      on-profile:

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

  springdoc:
    swagger-ui:
      enabled: false
      disable-swagger-default-url: true
    api-docs:
      enabled: false

app:
  frontend-url: https://tudominio.com
  security:
    jwt:
      secret: 51f1ebd91950319c7c05dfff4bfed4e89535eeccc9d8336c45de6150216e0cd97c3cc9041b5fdf3cad8631069dccc2fd7800e623446ffc78ab85184580cb9f9b2eed98a27c429fbc5974b16cef1a7a3a820f49568994039b4b1e5c1b28a5841023e7344583feae70f520a13789244edf769cf025bf16ea5d93d199b3b00d15fa87df8fa1be3514a3d0cbd4d67edb482597a1882e8c2fc7b62534853530e500b7b451c5fd2616d3c2778af628e2ce14210c4719649116abec8392564c653983e6580c148e7172ca1a61ff96efb58c0b254a237a0b07081b5762d75ac2a657489e1c9147dff1d7f7fd0afae53131b6c4bb1dcf75fec4e11af3ad237b95128b8f55
      access-expiration: 86400
      refresh-expiration: 604800
  payments:
    stripe:
      api-key: ${STRIPE_API_KEY}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET}

logging:
  level:
    root: warn
    org.springframework: warn
    com.axconstantino.reservationsystem: info
  file:
    name: /var/log/app/booking-app.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true